server:
  port: 8082

spring:
  profiles:
    active: qa

---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: Spring-boot-code
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Coder@2025#
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to Spring Boot Code!!

---

spring:
  config:
    activate:
      on-profile: qa
  application:
    name: Spring-boot-code
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Coder@2025#
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to Spring Boot Code!!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "beans,env"
---

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: Spring-boot-code
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Coder@2025#
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to Spring Boot Code!!